# Use the README file as a reference to customize settings.

Organisation:
  fields:
    default: name
    form: name, blurb, logo
    options:
      selectors: parent
  relationships: parent
  application: Application
